Repository netobserv/netobserv-ebpf-agent, pull requests merged in 2023-07, with the labels that each got.

#117 NETOBSERV-1112: Add TCP RTT calculation to ebpf-agent and userspace.
  bpf/configs.h
  bpf/flows.c
  bpf/maps_definition.h
  bpf/rtt_tracker.h
  bpf/types.h
  bpf/utils.h
  docs/config.md
  docs/rtt_calculations.md
  examples/flowlogs-dump/server/flowlogs-dump-collector.go
  pkg/agent/agent.go
  pkg/agent/config.go
  pkg/ebpf/bpf_bpfeb.go
  pkg/ebpf/bpf_bpfeb.o
  pkg/ebpf/bpf_bpfel.go
  pkg/ebpf/bpf_bpfel.o
  pkg/ebpf/tracer.go
  pkg/exporter/proto.go
  pkg/flow/record.go
  pkg/flow/record_test.go
  pkg/pbflow/flow.pb.go
  pkg/pbflow/flow_grpc.pb.go
  proto/flow.proto
Labels: enhancement, ok-to-test, jira/valid-reference, lgtm, approved

#144 NETOBSERV-1129: Add kernel version chk to disable hooks not supported on older version
  pkg/ebpf/bpf_bpfeb.o
  pkg/ebpf/bpf_bpfel.o
  pkg/ebpf/tracer.go
  pkg/pbflow/flow.pb.go
  pkg/pbflow/flow_grpc.pb.go
  pkg/utils/utils.go
  pkg/utils/utils_test.go
Labels: jira/valid-reference, lgtm, approved

#148 Upgrade linter - fix found issues - use go1.20
  .github/workflows/pull_request.yml
  .github/workflows/pull_request_e2e.yml
  .github/workflows/push_image.yml
  .github/workflows/push_image_pr.yml
  .github/workflows/release.yml
  .golangci.yml
  Dockerfile
  Makefile
  examples/performance/Dockerfile_packet_counter
  go.mod
  scripts/generators.Dockerfile
Labels: lgtm, approved

#149 NETOBSERV-1190: update dns tracker to calc latency instead of TS
  bpf/dns_tracker.h
  bpf/maps_definition.h
  bpf/types.h
  examples/flowlogs-dump/server/flowlogs-dump-collector.go
  pkg/ebpf/bpf_bpfeb.go
  pkg/ebpf/bpf_bpfeb.o
  pkg/ebpf/bpf_bpfel.go
  pkg/ebpf/bpf_bpfel.o
  pkg/exporter/proto.go
  pkg/flow/account_test.go
  pkg/flow/record.go
  pkg/flow/record_test.go
  pkg/grpc/grpc_test.go
  pkg/pbflow/flow.pb.go
  proto/flow.proto
Labels: ok-to-test, jira/valid-reference, lgtm, approved

#150 github ok-to-test: add more info in comment
  .github/workflows/push_image_pr.yml
Labels: lgtm, approved

#151 fix build for s390x and ppc64le
  pkg/utils/utils.go
Labels: ok-to-test, lgtm, approved

#153 NETOBSERV-1199: Socket doesn't always have valid if_index so we can't use it as key
  bpf/dns_tracker.h
  bpf/types.h
  pkg/ebpf/bpf_bpfeb.go
  pkg/ebpf/bpf_bpfeb.o
  pkg/ebpf/bpf_bpfel.go
  pkg/ebpf/bpf_bpfel.o
Labels: ok-to-test, qe-approved, jira/valid-reference, lgtm, approved

#152 NETOBSERV-1197: Generalize TCPDrop to include other protocols
  bpf/flows.c
  bpf/pkt_drops.h
  bpf/types.h
  bpf/utils.h
  pkg/agent/agent.go
  pkg/agent/config.go
  pkg/ebpf/bpf_bpfeb.go
  pkg/ebpf/bpf_bpfeb.o
  pkg/ebpf/bpf_bpfel.go
  pkg/ebpf/bpf_bpfel.o
  pkg/ebpf/tracer.go
  pkg/exporter/proto.go
  pkg/flow/record_test.go
  pkg/grpc/grpc_test.go
  pkg/pbflow/flow.pb.go
  proto/flow.proto
Labels: ok-to-test, jira/valid-reference, lgtm, approved

#162 Avoid using LRU hashmap because they consume lots of memory
  bpf/maps_definition.h
  pkg/ebpf/bpf_bpfeb.go
  pkg/ebpf/bpf_bpfeb.o
  pkg/ebpf/bpf_bpfel.go
  pkg/ebpf/bpf_bpfel.o
  pkg/pbflow/flow.pb.go
  pkg/pbflow/flow_grpc.pb.go
Labels: ok-to-test, lgtm, approved

#161 NETOBSERV-1198: drop_cause enum in vmlinux are based off old kernel
  bpf/headers/vmlinux.h
  bpf/pkt_drops.h
  pkg/ebpf/bpf_bpfeb.o
  pkg/ebpf/bpf_bpfel.o
Labels: qe-approved, jira/valid-reference, lgtm, approved

#165 Shrink DNSMap if DNS not enabled to save memory
  pkg/ebpf/tracer.go
Labels: ok-to-test, lgtm, approved
