Repository netobserv/netobserv-ebpf-agent, pull requests merged in 2023-10, with the labels that each got.

#196 close all maps when agent is terminating
  pkg/ebpf/tracer.go
Labels: lgtm, approved

#195 NETOBSERV-926: Fix kafka and connection tracking
  pkg/agent/agent.go
Labels: ok-to-test, qe-approved, jira/valid-reference, lgtm, approved

#158 NETOBSERV-588 Add IPv4/6 DSCP field to the exported flow
  bpf/flows.c
  bpf/types.h
  bpf/utils.h
  examples/flowlogs-dump/server/flowlogs-dump-collector.go
  go.mod
  pkg/decode/decode_protobuf.go
  pkg/decode/decode_protobuf_test.go
  pkg/ebpf/bpf_bpfeb.go
  pkg/ebpf/bpf_bpfeb.o
  pkg/ebpf/bpf_bpfel.go
  pkg/ebpf/bpf_bpfel.o
  pkg/exporter/proto.go
  pkg/flow/record.go
  pkg/flow/record_test.go
  pkg/pbflow/flow.pb.go
  pkg/pbflow/flow_grpc.pb.go
  proto/flow.proto
Labels: ok-to-test, qe-approved, lgtm, approved

#111 Filter interfaces by their associated IPs
  docs/config.md
  go.mod
  go.sum
  pkg/agent/agent.go
  pkg/agent/config.go
  pkg/agent/filter.go
  pkg/agent/filter_test.go
  pkg/agent/packets_agent.go
  vendor/modules.txt
Labels: no-doc, no-qe, lgtm, approved

#207 NETOBSERV-926: Fix kafka writer configuration ... [1.4 backport]
  pkg/agent/agent.go
Labels: ok-to-test, qe-approved, jira/valid-reference, lgtm, approved

#209 Workflow: build images from release branches
  .github/workflows/push_image.yml
Labels: lgtm, approved

#213 update github actions to use go1.21
  .github/workflows/pull_request.yml
  .github/workflows/pull_request_e2e.yml
  .github/workflows/push_image.yml
  .github/workflows/push_image_pr.yml
  .github/workflows/release.yml
  Makefile
  go.mod
  go.sum
  scripts/generators.Dockerfile
  vendor/modules.txt
Labels: lgtm, approved

#206 NETOBSERV-1245: NETOBSERV-1304: fix TCP DNS query
  bpf/configs.h
  bpf/dns_tracker.h
  bpf/flows.c
  bpf/types.h
  pkg/ebpf/bpf_bpfeb.go
  pkg/ebpf/bpf_bpfeb.o
  pkg/ebpf/bpf_bpfel.go
  pkg/ebpf/bpf_bpfel.o
  pkg/ebpf/tracer.go
Labels: ok-to-test, qe-approved, jira/valid-reference, lgtm, approved
