Repository netobserv/netobserv-ebpf-agent, pull requests merged in 2023-06, with the labels that each got.

#132 update agent spec for profiling docs
  docs/profiling.md
Labels: lgtm, approved

#133 NETOBSERV-1091: remove CO-RE file and extensions as that causes douple allocations
  bpf/flows.c
  bpf/headers/bpf_core_read.h
  pkg/ebpf/bpf_bpfeb.o
  pkg/ebpf/bpf_bpfel.o
  scripts/update-bpf-headers.sh
Labels: ok-to-test, qe-approved, jira/valid-reference, lgtm, approved

#134 NETOBSERV-1091:: remove CO-RE file and extensions as that causes douple allocations [backport]
  bpf/flows.c
  bpf/headers/bpf_core_read.h
  pkg/ebpf/bpf_bpfeb.o
  pkg/ebpf/bpf_bpfel.o
  scripts/update-bpf-headers.sh
Labels: jira/valid-reference, lgtm, approved

#136 Fix makefile image-build with podman
  Makefile
Labels: no-doc, no-qe, lgtm, approved

#138 Fix make docker-generate issue #137
  scripts/generators.Dockerfile
Labels: no-doc, no-qe, lgtm

#139 Add IBM Z (s390x)
  .github/workflows/push_image.yml
  .github/workflows/release.yml
Labels: no-doc, no-qe, lgtm, approved

#140 NETOBSERV-1103: optimize ebpf agent map memory and cpu usage
  bpf/flows.c
  bpf/headers/bpf_core_read.h
  pkg/agent/agent.go
  pkg/agent/agent_test.go
  pkg/agent/config.go
  pkg/ebpf/bpf_bpfeb.o
  pkg/ebpf/bpf_bpfel.o
  pkg/ebpf/tracer.go
  pkg/exporter/ipfix.go
  pkg/flow/tracer_map.go
  pkg/flow/tracer_ringbuf.go
  pkg/test/tracer_fake.go
  scripts/update-bpf-headers.sh
Labels: jira/valid-reference, lgtm, approved

#115 NETOBSERV-1061: Add TCP drop and DNS tracking hooks
  bpf/configs.h
  bpf/dns_tracker.h
  bpf/flow.h
  bpf/flows.c
  bpf/maps_definition.h
  bpf/tcp_drops.h
  bpf/utils.h
  e2e/cluster/base/04-agent.yml
  e2e/ipfix/manifests/30-agent.yml
  e2e/kafka/manifests/30-agent.yml
  examples/flowlogs-dump/server/flowlogs-dump-collector.go
  pkg/agent/agent.go
  pkg/agent/config.go
  pkg/ebpf/bpf_bpfeb.go
  pkg/ebpf/bpf_bpfeb.o
  pkg/ebpf/bpf_bpfel.go
  pkg/ebpf/bpf_bpfel.o
  pkg/ebpf/tracer.go
  pkg/exporter/kafka_proto_test.go
  pkg/exporter/proto.go
  pkg/flow/account.go
  pkg/flow/account_test.go
  pkg/flow/record.go
  pkg/flow/record_test.go
  pkg/flow/tracer_map.go
  pkg/grpc/grpc_test.go
  pkg/pbflow/flow.pb.go
  proto/flow.proto
  vendor/github.com/cilium/ebpf/link/cgroup.go
  vendor/github.com/cilium/ebpf/link/doc.go
  vendor/github.com/cilium/ebpf/link/iter.go
  vendor/github.com/cilium/ebpf/link/kprobe.go
  vendor/github.com/cilium/ebpf/link/kprobe_multi.go
  vendor/github.com/cilium/ebpf/link/link.go
  vendor/github.com/cilium/ebpf/link/netns.go
  vendor/github.com/cilium/ebpf/link/perf_event.go
  vendor/github.com/cilium/ebpf/link/platform.go
  vendor/github.com/cilium/ebpf/link/program.go
  vendor/github.com/cilium/ebpf/link/query.go
  vendor/github.com/cilium/ebpf/link/raw_tracepoint.go
  vendor/github.com/cilium/ebpf/link/socket_filter.go
  vendor/github.com/cilium/ebpf/link/syscalls.go
  vendor/github.com/cilium/ebpf/link/tracepoint.go
  vendor/github.com/cilium/ebpf/link/tracing.go
  vendor/github.com/cilium/ebpf/link/uprobe.go
  vendor/github.com/cilium/ebpf/link/xdp.go
  vendor/modules.txt
Labels: enhancement, ok-to-test, jira/valid-reference, lgtm, approved
