Repository netobserv/netobserv-ebpf-agent, pull requests merged in 2023-04, with the labels that each got.

#107 NETOBSERV-926: Added key to kafka message for connection tracking consistency
  pkg/exporter/kafka_proto.go
  pkg/exporter/kafka_proto_test.go
Labels: jira/valid-reference, lgtm, approved

#108 NETOBSERV-977: some interfaces on single stack cluster can have both ipv4 and ipv6 linklocal
  pkg/agent/ip.go
Labels: ok-to-test, qe-approved, jira/valid-reference, lgtm, approved

#109 NETOBSERV-977: some interfaces could have both ipv4 and ipv6 linklocal [backport]
  pkg/agent/ip.go
Labels: ok-to-test, qe-approved, jira/valid-reference, lgtm, approved

#110 cleanup kernel code and use vmlinux header for kernel structs and apis
  bpf/flow.h
  bpf/flows.c
  bpf/headers/bpf_core_read.h
  bpf/headers/bpf_helper_defs.h
  bpf/headers/bpf_helpers.h
  bpf/headers/bpf_tracing.h
  bpf/headers/vmlinux.h
  pkg/ebpf/bpf_bpfeb.o
  pkg/ebpf/bpf_bpfel.o
  scripts/update-bpf-headers.sh
Labels: no-doc, no-qe, lgtm, approved
