Repository netobserv/netobserv-ebpf-agent, pull requests merged in 2024-12, with the labels that each got.

#466 NETOBSERV-1994: remove unneeded bpf map update calls
  bpf/dns_tracker.h
  bpf/flows.c
  bpf/flows_filter.h
  bpf/network_events_monitoring.h
  bpf/pkt_drops.h
  bpf/rtt_tracker.h
  bpf/types.h
  pkg/ebpf/bpf_arm64_bpfel.o
  pkg/ebpf/bpf_powerpc_bpfel.o
  pkg/ebpf/bpf_s390_bpfeb.o
  pkg/ebpf/bpf_x86_bpfel.o
Labels: ok-to-test, qe-approved, jira/valid-reference, lgtm, approved

#469 NETOBSERV-1995: Use global map, spinlock, split maps
  .golangci.yml
  Makefile
  bpf/flows.c
  bpf/flows_filter.h
  bpf/maps_definition.h
  bpf/network_events_monitoring.h
  bpf/pca.h
  bpf/pkt_drops.h
  bpf/rtt_tracker.h
  bpf/types.h
  bpf/utils.h
  docs/architecture.md
  pkg/agent/agent.go
  pkg/agent/agent_test.go
  pkg/decode/decode_protobuf.go
  pkg/decode/decode_protobuf_test.go
  pkg/ebpf/bpf_arm64_bpfel.go
  pkg/ebpf/bpf_arm64_bpfel.o
  pkg/ebpf/bpf_powerpc_bpfel.go
  pkg/ebpf/bpf_powerpc_bpfel.o
  pkg/ebpf/bpf_s390_bpfeb.go
  pkg/ebpf/bpf_s390_bpfeb.o
  pkg/ebpf/bpf_x86_bpfel.go
  pkg/ebpf/bpf_x86_bpfel.o
  pkg/exporter/converters_test.go
  pkg/exporter/direct_flp_test.go
  pkg/exporter/grpc_proto_test.go
  pkg/exporter/ipfix.go
  pkg/exporter/kafka_proto.go
  pkg/exporter/kafka_proto_test.go
  pkg/flow/account.go
  pkg/flow/account_test.go
  pkg/flow/decorator.go
  pkg/flow/deduper.go
  pkg/flow/deduper_test.go
  pkg/flow/tracer_map.go
  pkg/flow/tracer_map_test.go
  pkg/model/flow_content.go
  pkg/model/record.go
  pkg/model/record_test.go
  pkg/pbflow/proto.go
  pkg/test/tracer_fake.go
  pkg/tracer/tracer.go
  pkg/tracer/tracer_legacy.go
Labels: ok-to-test, qe-approved, jira/valid-reference, lgtm, approved

#438 NETOBSERV-1965: eBPF packet translation tracker
  bpf/configs.h
  bpf/flows.c
  bpf/headers/vmlinux_amd64.h
  bpf/headers/vmlinux_arm64.h
  bpf/headers/vmlinux_ppc64le.h
  bpf/pkt_translation.h
  bpf/types.h
  pkg/agent/agent.go
  pkg/agent/config.go
  pkg/decode/decode_protobuf.go
  pkg/decode/decode_protobuf_test.go
  pkg/ebpf/bpf_arm64_bpfel.go
  pkg/ebpf/bpf_arm64_bpfel.o
  pkg/ebpf/bpf_powerpc_bpfel.go
  pkg/ebpf/bpf_powerpc_bpfel.o
  pkg/ebpf/bpf_s390_bpfeb.go
  pkg/ebpf/bpf_s390_bpfeb.o
  pkg/ebpf/bpf_x86_bpfel.go
  pkg/ebpf/bpf_x86_bpfel.o
  pkg/ebpf/gen.go
  pkg/model/flow_content.go
  pkg/model/record.go
  pkg/model/record_test.go
  pkg/pbflow/flow.pb.go
  pkg/pbflow/proto.go
  pkg/tracer/tracer.go
  proto/flow.proto
Labels: ok-to-test, jira/valid-reference, lgtm, approved

#443 SDN-5393: eBPF agent intg with bpfman for ebpf progs life cycle mgmts
  .github/workflows/push_image.yml
  .github/workflows/push_image_pr.yml
  Containerfile.bytecode.multi.arch
  Makefile
  bpf/flows.c
  bpf/maps_definition.h
  bpf/pca.h
  hack/build-bytecode-images-multi.sh
  pkg/agent/agent.go
  pkg/agent/config.go
  pkg/agent/packets_agent.go
  pkg/ebpf/bpf_arm64_bpfel.o
  pkg/ebpf/bpf_powerpc_bpfel.o
  pkg/ebpf/bpf_s390_bpfeb.o
  pkg/ebpf/bpf_x86_bpfel.o
  pkg/tracer/tracer.go
Labels: jira/valid-reference, lgtm, approved

#473 NETOBSERV-2005: Support multiple flow filter rules using json fmt string
  bpf/flows.c
  bpf/flows_filter.h
  bpf/network_events_monitoring.h
  bpf/pca.h
  bpf/pkt_drops.h
  bpf/pkt_translation.h
  bpf/rtt_tracker.h
  bpf/types.h
  bpf/utils.h
  pkg/agent/agent.go
  pkg/agent/config.go
  pkg/agent/packets_agent.go
  pkg/decode/decode_protobuf.go
  pkg/ebpf/bpf_arm64_bpfel.go
  pkg/ebpf/bpf_arm64_bpfel.o
  pkg/ebpf/bpf_powerpc_bpfel.go
  pkg/ebpf/bpf_powerpc_bpfel.o
  pkg/ebpf/bpf_s390_bpfeb.go
  pkg/ebpf/bpf_s390_bpfeb.o
  pkg/ebpf/bpf_x86_bpfel.go
  pkg/ebpf/bpf_x86_bpfel.o
  pkg/exporter/converters_test.go
  pkg/model/flow_content.go
  pkg/model/record_test.go
  pkg/pbflow/flow.pb.go
  pkg/pbflow/proto.go
  pkg/tracer/flow_filter.go
  pkg/tracer/tracer.go
  proto/flow.proto
Labels: ok-to-test, jira/valid-reference, lgtm, approved

#485 make sure to remove pca map pinning
  pkg/tracer/tracer.go
Labels: ok-to-test, lgtm, approved

#448 Improve e2e troubleshooting
  Makefile
  README.md
  e2e/README.md
  e2e/basic/common.go
  e2e/basic/flow_test.go
  e2e/cluster/base/02-loki.yml
  e2e/cluster/kind.go
  e2e/cluster/kind_test.go
  e2e/cluster/tester/loki.go
  e2e/cluster/tester/pods.go
  e2e/ipfix/ipfix_test.go
  e2e/kafka/kafka_test.go
  e2e/kafka/manifests/10-kafka-crd.yml
Labels: no-doc, no-qe, lgtm, approved

#484 Adding version label in downstream build
  Dockerfile.downstream
Labels: lgtm, approved

#494 Memset dns id to 0
  bpf/dns_tracker.h
  pkg/ebpf/bpf_arm64_bpfel.o
  pkg/ebpf/bpf_powerpc_bpfel.o
  pkg/ebpf/bpf_s390_bpfeb.o
  pkg/ebpf/bpf_x86_bpfel.o
Labels: ok-to-test, lgtm, approved

#490 move to go 1.23
  .github/workflows/pull_request.yml
  .github/workflows/push_image.yml
  .github/workflows/push_image_pr.yml
  .github/workflows/release.yml
  Dockerfile
  Dockerfile.downstream
  Makefile
  examples/performance/Dockerfile_packet_counter
  hack/update-build.sh
  scripts/generators.Dockerfile
Labels: lgtm, approved

#488 optimize filter sampling logic when filtering not enabled
  bpf/flows.c
  bpf/flows_filter.h
  bpf/network_events_monitoring.h
  bpf/pkt_drops.h
  bpf/pkt_translation.h
  bpf/rtt_tracker.h
  bpf/types.h
  bpf/utils.h
  pkg/ebpf/bpf_arm64_bpfel.go
  pkg/ebpf/bpf_arm64_bpfel.o
  pkg/ebpf/bpf_powerpc_bpfel.go
  pkg/ebpf/bpf_powerpc_bpfel.o
  pkg/ebpf/bpf_s390_bpfeb.go
  pkg/ebpf/bpf_s390_bpfeb.o
  pkg/ebpf/bpf_x86_bpfel.go
  pkg/ebpf/bpf_x86_bpfel.o
  pkg/flow/tracer_map_test.go
  pkg/model/flow_content.go
  pkg/model/record_test.go
  pkg/tracer/tracer.go
Labels: ok-to-test, qe-approved, lgtm
