Repository netobserv/netobserv-ebpf-agent, pull requests merged in 2024-02, with the labels that each got.

#260 Filter out sockets for loopback and unknown interfaces
  bpf/pkt_drops.h
  bpf/rtt_tracker.h
  pkg/ebpf/bpf_arm64_bpfel.o
  pkg/ebpf/bpf_powerpc_bpfel.o
  pkg/ebpf/bpf_s390_bpfeb.o
  pkg/ebpf/bpf_x86_bpfel.o
Labels: ok-to-test, lgtm, approved

#261 Filter out sockets for loopback and unknown interfaces (Backport 1.5)
  bpf/pkt_drops.h
  bpf/rtt_tracker.h
  pkg/ebpf/bpf_arm64_bpfel.o
  pkg/ebpf/bpf_powerpc_bpfel.o
  pkg/ebpf/bpf_s390_bpfeb.o
  pkg/ebpf/bpf_x86_bpfel.o
Labels: ok-to-test, lgtm, approved

#267 NETOBSERV-1507: some arch still missing fentry hook types fallback to kprobe [BP 1.5]
  bpf/rtt_tracker.h
  pkg/ebpf/bpf_arm64_bpfel.go
  pkg/ebpf/bpf_arm64_bpfel.o
  pkg/ebpf/bpf_powerpc_bpfel.go
  pkg/ebpf/bpf_powerpc_bpfel.o
  pkg/ebpf/bpf_s390_bpfeb.go
  pkg/ebpf/bpf_s390_bpfeb.o
  pkg/ebpf/bpf_x86_bpfel.go
  pkg/ebpf/bpf_x86_bpfel.o
  pkg/ebpf/tracer.go
Labels: jira/valid-reference, lgtm, approved

#265 NETOBSERV-1507: some arch still missing fentry hook fall back to kprobe
  bpf/rtt_tracker.h
  pkg/ebpf/bpf_arm64_bpfel.go
  pkg/ebpf/bpf_arm64_bpfel.o
  pkg/ebpf/bpf_powerpc_bpfel.go
  pkg/ebpf/bpf_powerpc_bpfel.o
  pkg/ebpf/bpf_s390_bpfeb.go
  pkg/ebpf/bpf_s390_bpfeb.o
  pkg/ebpf/bpf_x86_bpfel.go
  pkg/ebpf/bpf_x86_bpfel.o
  pkg/ebpf/tracer.go
Labels: ok-to-test, jira/valid-reference, lgtm, approved

#263 NETOBSERV-557: add eBPF agent metrics for troubleshooting
  go.mod
  pkg/agent/agent.go
  pkg/agent/config.go
  pkg/agent/packets_agent.go
  pkg/ebpf/tracer.go
  pkg/exporter/grpc_proto.go
  pkg/exporter/grpc_proto_test.go
  pkg/exporter/kafka_proto.go
  pkg/exporter/kafka_proto_test.go
  pkg/flow/account.go
  pkg/flow/account_test.go
  pkg/flow/tracer_map.go
  pkg/flow/tracer_ringbuf.go
  pkg/metrics/metrics.go
  pkg/metrics/metrics_test.go
  pkg/prometheus/prom_server.go
  pkg/prometheus/prom_server_test.go
  pkg/test/tracer_fake.go
Labels: jira/valid-reference, lgtm, approved

#279 bump FLP
  go.mod
  go.sum
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/api/api.go
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/api/encode_prom.go
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/pipeline/encode/encode_prom.go
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/pipeline/encode/encode_prom_metric.go
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/pipeline/encode/metrics_common.go
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/pipeline/encode/opentelemetry/encode_otlpmetrics.go
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/pipeline/write/write_ipfix.go
  vendor/go.opentelemetry.io/otel/exporters/otlp/otlpmetric/otlpmetrichttp/config.go
  vendor/go.opentelemetry.io/otel/exporters/otlp/otlpmetric/otlpmetrichttp/doc.go
  vendor/go.opentelemetry.io/otel/exporters/otlp/otlpmetric/otlpmetrichttp/internal/oconf/options.go
  vendor/go.opentelemetry.io/otel/exporters/otlp/otlpmetric/otlpmetrichttp/version.go
  vendor/modules.txt
Labels: ok-to-test, lgtm, approved

#278 Share errors counter across components
  pkg/agent/agent.go
  pkg/exporter/grpc_proto.go
  pkg/exporter/kafka_proto.go
  pkg/exporter/kafka_proto_test.go
  pkg/flow/tracer_map.go
  pkg/metrics/metrics.go
Labels: lgtm, approved

#277 Add KinD deployment env for developement
  Makefile
  README.md
  scripts/agent.yml
  scripts/kind-cluster.sh
Labels: lgtm, approved
