Repository netobserv/netobserv-ebpf-agent, pull requests merged in 2024-01, with the labels that each got.

#244 update kind image to recent image
  e2e/cluster/kind.go
Labels: no-doc, no-qe, lgtm, approved

#247 NETOBSERV-1451: Bump ubi 9.3 / go 1.21
  .golangci.yml
  Dockerfile
  examples/performance/Dockerfile_packet_counter
Labels: no-doc, no-qe, jira/valid-reference, lgtm, approved

#248 s390x arch work around till bpf2go pr#1308 is available
  Makefile
  pkg/ebpf/bpf_bpfeb_s390x.go
Labels: lgtm, approved

#233 NETOBSERV-1298: Interface name wasn't populated yet so add func to find ifname
  pkg/decode/decode_protobuf.go
  pkg/decode/decode_protobuf_test.go
  pkg/exporter/proto.go
  pkg/flow/deduper.go
  pkg/flow/deduper_test.go
  pkg/utils/utils.go
Labels: ok-to-test, jira/valid-reference, lgtm, approved

#249 updated README and yml files
  deployments/README.md
  deployments/flp-daemonset-cap.yml
  deployments/flp-daemonset.yml
  deployments/flp-service.yml
  deployments/perms.yml
Labels: lgtm, approved

#250 use unknown for interface we can't detect instead of ""
  pkg/utils/utils.go
Labels: lgtm, approved

#251 use cached api to retrieve interface name to avoid highcpu
  pkg/agent/agent.go
  pkg/flow/deduper.go
  pkg/flow/deduper_test.go
  pkg/utils/utils.go
Labels: ok-to-test, lgtm, approved

#255 pickup cilium fix for bpf2go tool for s390x target and remove Makefile workaround
  Makefile
  go.mod
  go.sum
  pkg/ebpf/bpf_arm64_bpfel.go
  pkg/ebpf/bpf_arm64_bpfel.o
  pkg/ebpf/bpf_powerpc_bpfel.go
  pkg/ebpf/bpf_powerpc_bpfel.o
  pkg/ebpf/bpf_s390_bpfeb.go
  pkg/ebpf/bpf_s390_bpfeb.o
  pkg/ebpf/bpf_x86_bpfel.go
  pkg/ebpf/bpf_x86_bpfel.o
  vendor/github.com/cilium/ebpf/ARCHITECTURE.md
  vendor/github.com/cilium/ebpf/CODEOWNERS
  vendor/github.com/cilium/ebpf/CONTRIBUTING.md
  vendor/github.com/cilium/ebpf/Makefile
  vendor/github.com/cilium/ebpf/README.md
  vendor/github.com/cilium/ebpf/attachtype_string.go
  vendor/github.com/cilium/ebpf/btf/btf.go
  vendor/github.com/cilium/ebpf/btf/core.go
  vendor/github.com/cilium/ebpf/btf/ext_info.go
  vendor/github.com/cilium/ebpf/btf/marshal.go
  vendor/github.com/cilium/ebpf/btf/traversal.go
  vendor/github.com/cilium/ebpf/btf/types.go
  vendor/github.com/cilium/ebpf/cpu.go
  vendor/github.com/cilium/ebpf/elf_reader.go
  vendor/github.com/cilium/ebpf/elf_sections.go
  vendor/github.com/cilium/ebpf/internal/sys/mapflags_string.go
  vendor/github.com/cilium/ebpf/internal/sys/syscall.go
  vendor/github.com/cilium/ebpf/internal/sys/types.go
  vendor/github.com/cilium/ebpf/internal/sysenc/buffer.go
  vendor/github.com/cilium/ebpf/internal/unix/types_linux.go
  vendor/github.com/cilium/ebpf/internal/unix/types_other.go
  vendor/github.com/cilium/ebpf/link/anchor.go
  vendor/github.com/cilium/ebpf/link/cgroup.go
  vendor/github.com/cilium/ebpf/link/link.go
  vendor/github.com/cilium/ebpf/link/program.go
  vendor/github.com/cilium/ebpf/link/query.go
  vendor/github.com/cilium/ebpf/link/syscalls.go
  vendor/github.com/cilium/ebpf/link/tcx.go
  vendor/github.com/cilium/ebpf/linker.go
  vendor/github.com/cilium/ebpf/map.go
  vendor/github.com/cilium/ebpf/marshalers.go
  vendor/github.com/cilium/ebpf/perf/reader.go
  vendor/github.com/cilium/ebpf/prog.go
  vendor/github.com/cilium/ebpf/ringbuf/reader.go
  vendor/github.com/cilium/ebpf/run-tests.sh
  vendor/github.com/cilium/ebpf/syscalls.go
  vendor/github.com/cilium/ebpf/types.go
  vendor/github.com/cilium/ebpf/types_string.go
  vendor/modules.txt
Labels: lgtm, approved
