Repository netobserv/netobserv-ebpf-agent, pull requests merged in 2024-04, with the labels that each got.

#309 NETOBSERV-1595: generate BPF from CI
  .github/workflows/pull_request.yml
  Dockerfile
  Makefile
  e2e/basic/manifests/pods.yml
  examples/performance/Dockerfile_packet_counter
  pkg/ebpf/bpf_arm64_bpfel.o
  pkg/ebpf/bpf_powerpc_bpfel.o
  pkg/ebpf/bpf_s390_bpfeb.o
  pkg/ebpf/bpf_x86_bpfel.o
  pkg/pbpacket/packet.pb.go
  pkg/pbpacket/packet_grpc.pb.go
Labels: ok-to-test, jira/valid-reference, lgtm, approved

#312 codecov v4
  .github/workflows/pull_request.yml
Labels: lgtm, approved

#307 NETOBSERV-1478: Add eBPF Agent filtering capability
  bpf/configs.h
  bpf/flows.c
  bpf/flows_filter.h
  bpf/maps_definition.h
  bpf/pkt_drops.h
  bpf/types.h
  docs/config.md
  docs/flow_filtering.md
  pkg/agent/agent.go
  pkg/agent/config.go
  pkg/ebpf/bpf_arm64_bpfel.go
  pkg/ebpf/bpf_arm64_bpfel.o
  pkg/ebpf/bpf_powerpc_bpfel.go
  pkg/ebpf/bpf_powerpc_bpfel.o
  pkg/ebpf/bpf_s390_bpfeb.go
  pkg/ebpf/bpf_s390_bpfeb.o
  pkg/ebpf/bpf_x86_bpfel.go
  pkg/ebpf/bpf_x86_bpfel.o
  pkg/ebpf/flow_filter.go
  pkg/ebpf/flow_filter_test.go
  pkg/ebpf/tracer.go
  pkg/metrics/metrics.go
Labels: ok-to-test, qe-approved, jira/valid-reference, lgtm, approved

#314 Add eBPF C code linter
  Makefile
  bpf/dns_tracker.h
  bpf/flows.c
  bpf/flows_filter.h
  bpf/maps_definition.h
  bpf/pca.h
  bpf/pkt_drops.h
  bpf/rtt_tracker.h
  bpf/types.h
  bpf/utils.h
  pkg/ebpf/bpf_arm64_bpfel.o
  pkg/ebpf/bpf_powerpc_bpfel.o
  pkg/ebpf/bpf_s390_bpfeb.o
  pkg/ebpf/bpf_x86_bpfel.o
Labels: no-doc, no-qe, lgtm, approved

#313 Avoid unnecessary call when sampling=1
  bpf/flows.c
  pkg/ebpf/bpf_arm64_bpfel.o
  pkg/ebpf/bpf_powerpc_bpfel.o
  pkg/ebpf/bpf_s390_bpfeb.o
  pkg/ebpf/bpf_x86_bpfel.o
Labels: lgtm, approved

#316 NETOBSERV-1605: reset ebpf global counters after reading them
  pkg/ebpf/tracer.go
Labels: ok-to-test, jira/valid-reference, lgtm, approved

#317 Codecov add env token from secret
  .github/workflows/pull_request.yml
Labels: lgtm, approved

#262 NETOBSERV-1473: migrating netobserv-agent to TCx for new kernels
  bpf/flows.c
  bpf/headers/vmlinux_amd64.h
  bpf/headers/vmlinux_arm64.h
  bpf/headers/vmlinux_s390.h
  bpf/pca.h
  pkg/agent/agent.go
  pkg/agent/packets_agent.go
  pkg/ebpf/bpf_arm64_bpfel.go
  pkg/ebpf/bpf_arm64_bpfel.o
  pkg/ebpf/bpf_powerpc_bpfel.go
  pkg/ebpf/bpf_powerpc_bpfel.o
  pkg/ebpf/bpf_s390_bpfeb.go
  pkg/ebpf/bpf_s390_bpfeb.o
  pkg/ebpf/bpf_x86_bpfel.go
  pkg/ebpf/bpf_x86_bpfel.o
  pkg/ebpf/tracer.go
  pkg/test/tracer_fake.go
Labels: ok-to-test, jira/valid-reference, lgtm, approved

#318 Allow flow filtering to coexists with pkt drop and rtt ebpf hooks
  bpf/flows.c
  bpf/pkt_drops.h
  bpf/rtt_tracker.h
  bpf/utils.h
  pkg/ebpf/bpf_arm64_bpfel.o
  pkg/ebpf/bpf_powerpc_bpfel.o
  pkg/ebpf/bpf_s390_bpfeb.o
  pkg/ebpf/bpf_x86_bpfel.o
Labels: ok-to-test, lgtm, approved

#325 Update mk
  Makefile
  go.mod
  go.sum
  vendor/github.com/cilium/ebpf/Makefile
  vendor/github.com/cilium/ebpf/README.md
  vendor/github.com/cilium/ebpf/btf/btf.go
  vendor/github.com/cilium/ebpf/btf/core.go
  vendor/github.com/cilium/ebpf/btf/ext_info.go
  vendor/github.com/cilium/ebpf/btf/kernel.go
  vendor/github.com/cilium/ebpf/btf/marshal.go
  vendor/github.com/cilium/ebpf/btf/traversal.go
  vendor/github.com/cilium/ebpf/btf/types.go
  vendor/github.com/cilium/ebpf/internal/math.go
  vendor/github.com/cilium/ebpf/internal/sys/syscall.go
  vendor/github.com/cilium/ebpf/internal/sys/types.go
  vendor/github.com/cilium/ebpf/internal/unix/types_linux.go
  vendor/github.com/cilium/ebpf/internal/unix/types_other.go
  vendor/github.com/cilium/ebpf/link/link.go
  vendor/github.com/cilium/ebpf/linker.go
  vendor/github.com/cilium/ebpf/map.go
  vendor/github.com/cilium/ebpf/perf/reader.go
  vendor/github.com/cilium/ebpf/perf/ring.go
  vendor/github.com/cilium/ebpf/prog.go
  vendor/modules.txt
Labels: lgtm, approved

#320 NETOBSERV-1473: fix ebpf program name for older kernel
  pkg/ebpf/tracer.go
Labels: qe-approved, jira/valid-reference, lgtm, approved

#327 update to fc40 and fix new linter error
  bpf/dns_tracker.h
  pkg/ebpf/bpf_arm64_bpfel.o
  pkg/ebpf/bpf_powerpc_bpfel.o
  pkg/ebpf/bpf_s390_bpfeb.o
  pkg/ebpf/bpf_x86_bpfel.o
  scripts/generators.Dockerfile
Labels: lgtm, approved
