Repository netobserv/netobserv-ebpf-agent, pull requests merged in 2024-10, with the labels that each got.

#426 NETOBSERV-1805: threads are leaking with continous adding and deletinng pods
  pkg/ifaces/watcher.go
Labels: ok-to-test, qe-approved, jira/valid-reference, lgtm, approved

#427 NETOBSERV-1805: threads are leaking with continous adding and deleting pods [BP 1.7]
  pkg/ifaces/watcher.go
Labels: ok-to-test, jira/valid-reference, lgtm, approved

#419 Add pkt drop filter support
  bpf/flows.c
  bpf/flows_filter.h
  bpf/headers/vmlinux_amd64.h
  bpf/headers/vmlinux_arm64.h
  bpf/headers/vmlinux_ppc64le.h
  bpf/headers/vmlinux_s390.h
  bpf/network_events_monitoring.h
  bpf/pca.h
  bpf/pkt_drops.h
  bpf/rtt_tracker.h
  bpf/types.h
  bpf/utils.h
  docs/flow_filtering.md
  pkg/agent/agent.go
  pkg/agent/config.go
  pkg/agent/packets_agent.go
  pkg/decode/decode_protobuf.go
  pkg/ebpf/bpf_arm64_bpfel.go
  pkg/ebpf/bpf_arm64_bpfel.o
  pkg/ebpf/bpf_powerpc_bpfel.go
  pkg/ebpf/bpf_powerpc_bpfel.o
  pkg/ebpf/bpf_s390_bpfeb.go
  pkg/ebpf/bpf_s390_bpfeb.o
  pkg/ebpf/bpf_x86_bpfel.go
  pkg/ebpf/bpf_x86_bpfel.o
  pkg/tracer/flow_filter.go
Labels: ok-to-test, lgtm, approved

#431 NETOBSERV-1633: Add prefetch configuration for konflux
  .tekton/netobserv-ebpf-agent-pull-request.yaml
  .tekton/netobserv-ebpf-agent-push.yaml
Labels: jira/valid-reference, lgtm, approved
