Repository netobserv/netobserv-ebpf-agent, pull requests merged in 2024-09, with the labels that each got.

#401 Need to differentiate between cached dns response vs incomplete ones [BP]
  bpf/dns_tracker.h
  pkg/decode/decode_protobuf.go
  pkg/decode/decode_protobuf_test.go
  pkg/ebpf/bpf_arm64_bpfel.o
  pkg/ebpf/bpf_powerpc_bpfel.o
  pkg/ebpf/bpf_s390_bpfeb.o
  pkg/ebpf/bpf_x86_bpfel.o
  pkg/flow/record.go
Labels: lgtm, approved

#402 Need to differentiate between cached dns response vs incomplete ones [BP]
  bpf/flows_filter.h
  pkg/ebpf/bpf_arm64_bpfel.o
  pkg/ebpf/bpf_powerpc_bpfel.o
  pkg/ebpf/bpf_s390_bpfeb.o
  pkg/ebpf/bpf_x86_bpfel.o
  pkg/flow/deduper.go
  pkg/flow/record.go
Labels: ok-to-test, lgtm, approved

#389 NETOBSERV-1803: Allow flow filtering for L4 protocols using two ports
  bpf/configs.h
  bpf/dns_tracker.h
  bpf/flows_filter.h
  bpf/types.h
  docs/flow_filtering.md
  pkg/agent/agent.go
  pkg/agent/config.go
  pkg/agent/packets_agent.go
  pkg/ebpf/bpf_arm64_bpfel.go
  pkg/ebpf/bpf_arm64_bpfel.o
  pkg/ebpf/bpf_powerpc_bpfel.go
  pkg/ebpf/bpf_powerpc_bpfel.o
  pkg/ebpf/bpf_s390_bpfeb.go
  pkg/ebpf/bpf_s390_bpfeb.o
  pkg/ebpf/bpf_x86_bpfel.go
  pkg/ebpf/bpf_x86_bpfel.o
  pkg/ebpf/flow_filter.go
  pkg/ebpf/flow_filter_test.go
  pkg/ebpf/tracer.go
Labels: jira/valid-reference, lgtm, approved

#400 Need to differentiate between cached dns response vs incomplete ones
  .github/workflows/pull_request.yml
  bpf/dns_tracker.h
  pkg/decode/decode_protobuf.go
  pkg/decode/decode_protobuf_test.go
  pkg/ebpf/bpf_arm64_bpfel.o
  pkg/ebpf/bpf_powerpc_bpfel.o
  pkg/ebpf/bpf_s390_bpfeb.o
  pkg/ebpf/bpf_x86_bpfel.o
  pkg/flow/deduper.go
  pkg/flow/record.go
Labels: lgtm, approved

#399 NETOBSERV-1805: make sure to cleanup pod veth's hooks when pods is deleted
  pkg/agent/agent.go
  pkg/agent/packets_agent.go
  pkg/ebpf/tracer.go
  pkg/ifaces/watcher.go
  pkg/test/tracer_fake.go
Labels: qe-approved, jira/valid-reference, lgtm, approved

#386 NETOBSERV-1792: Added update-build script to add downstream labels
  .tekton/netobserv-ebpf-agent-pull-request.yaml
  .tekton/netobserv-ebpf-agent-push.yaml
  hack/update-build.sh
Labels: jira/valid-reference, lgtm, approved

#413 NETOBSERV-1882 make sure pkt drop hook is disabled for PCA feature
  pkg/ebpf/tracer.go
Labels: ok-to-test, lgtm, approved

#421 fix codecov upload
  .github/workflows/push_image.yml
Labels: lgtm, approved

#423 NETOBSERV-1898 & NETOBSERV-1896: refactor pkt drop to be more efficient with using stack
  bpf/network_events_monitoring.h
  bpf/pkt_drops.h
  bpf/utils.h
  pkg/agent/packets_agent.go
  pkg/ebpf/bpf_arm64_bpfel.o
  pkg/ebpf/bpf_powerpc_bpfel.o
  pkg/ebpf/bpf_s390_bpfeb.o
  pkg/ebpf/bpf_x86_bpfel.o
  pkg/ebpf/flow_filter.go
  pkg/ebpf/flow_filter_test.go
Labels: qe-approved, jira/valid-reference, lgtm, approved

#424 NETOBSERV-1898 & NETOBSERV-1896: refactor pkt drop to be more efficient with using stack [BP 1.7]
  bpf/network_events_monitoring.h
  bpf/pkt_drops.h
  bpf/utils.h
  pkg/agent/packets_agent.go
  pkg/ebpf/bpf_arm64_bpfel.o
  pkg/ebpf/bpf_powerpc_bpfel.o
  pkg/ebpf/bpf_s390_bpfeb.o
  pkg/ebpf/bpf_x86_bpfel.o
  pkg/ebpf/flow_filter.go
  pkg/ebpf/flow_filter_test.go
Labels: ok-to-test, jira/valid-reference, lgtm, approved
