Repository netobserv/netobserv-ebpf-agent, pull requests merged in 2024-03, with the labels that each got.

#281 NETOBSERV-1533: refine metrics for dashboard creation
  pkg/agent/agent.go
  pkg/agent/agent_test.go
  pkg/agent/packets_agent.go
  pkg/ebpf/tracer.go
  pkg/exporter/grpc_proto.go
  pkg/exporter/grpc_proto_test.go
  pkg/exporter/kafka_proto.go
  pkg/exporter/kafka_proto_test.go
  pkg/flow/account.go
  pkg/flow/deduper.go
  pkg/flow/deduper_test.go
  pkg/flow/limiter.go
  pkg/flow/limiter_test.go
  pkg/flow/tracer_map.go
  pkg/flow/tracer_ringbuf.go
  pkg/metrics/metrics.go
  pkg/metrics/metrics_test.go
  pkg/test/tracer_fake.go
Labels: ok-to-test, jira/valid-reference, lgtm, approved

#285 Add direct-flp mode documentation
  docs/config.md
  pkg/agent/config.go
Labels: lgtm, approved

#296 fix e2e
  deployments/flp-daemonset-cap.yml
  deployments/flp-daemonset.yml
  deployments/flp-service.yml
  e2e/basic/common.go
  e2e/basic/flow_test.go
  e2e/cluster/base/03-flp.yml
  e2e/ipfix/ipfix_test.go
  e2e/kafka/kafka_test.go
  e2e/kafka/manifests/20-flp-transformer.yml
  go.mod
  go.sum
  vendor/github.com/minio/minio-go/v7/CREDITS
  vendor/github.com/minio/minio-go/v7/api.go
  vendor/github.com/minio/minio-go/v7/pkg/credentials/iam_aws.go
  vendor/github.com/minio/minio-go/v7/s3-endpoints.go
  vendor/github.com/minio/minio-go/v7/utils.go
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/api/write_grpc.go
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/config/config.go
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/pipeline/pipeline_builder.go
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/pipeline/write/grpc/client.go
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/pipeline/write/grpc/genericmap/genericmap.pb.go
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/pipeline/write/grpc/genericmap/genericmap_grpc.pb.go
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/pipeline/write/grpc/server.go
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/pipeline/write/write_grpc.go
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/pipeline/write/write_ipfix.go
  vendor/go.opentelemetry.io/otel/exporters/otlp/otlpmetric/otlpmetrichttp/internal/transform/metricdata.go
  vendor/go.opentelemetry.io/otel/exporters/otlp/otlpmetric/otlpmetrichttp/version.go
  vendor/go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracegrpc/options.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/modules.txt
Labels: lgtm, approved

#295 NETOBSERV-1514: drop go1.20 support
  .github/workflows/pull_request.yml
  .gitignore
  Makefile
  README.md
  go.mod
  go.sum
  pkg/pbflow/flow.pb.go
  scripts/generators.Dockerfile
Labels: jira/valid-reference, lgtm, approved

#297 Fix issue with inconsistent GenericMap output
  docs/config.md
  pkg/decode/decode_protobuf.go
  pkg/decode/decode_protobuf_test.go
  pkg/exporter/convert_flp.go
  pkg/exporter/converters_test.go
  pkg/exporter/direct_flp.go
  pkg/exporter/grpc_proto.go
  pkg/exporter/kafka_proto.go
  pkg/exporter/kafka_proto_test.go
  pkg/exporter/proto.go
  pkg/flow/record.go
  pkg/pbflow/proto.go
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/pipeline/write/write_ipfix.go
Labels: breaking-change, no-doc, no-qe, lgtm, approved

#269 NETOBSERV-1474: change dup mode to use list as the default
  pkg/agent/config.go
Labels: ok-to-test, qe-approved, jira/valid-reference, lgtm, approved

#291 NETOBSERV-1471 gRPC export for packet capture
  Makefile
  README.md
  deployments/flp-daemonset-cap.yml
  deployments/flp-daemonset.yml
  deployments/flp-service.yml
  docs/config.md
  e2e/cluster/base/04-agent.yml
  e2e/ipfix/manifests/30-agent.yml
  examples/flowlogs-dump/README.md
  examples/flowlogs-dump/server/flowlogs-dump-collector.go
  examples/packetcapture-dump/README.md
  examples/packetcapture-dump/client/packetcapture-client.go
  examples/performance/deployment.yml
  examples/performance/server/packet-counter-collector.go
  examples/systemd/netobserv-ebpf-agent
  pkg/agent/agent.go
  pkg/agent/agent_test.go
  pkg/agent/config.go
  pkg/agent/packets_agent.go
  pkg/exporter/grpc_packets.go
  pkg/exporter/grpc_proto.go
  pkg/exporter/grpc_proto_test.go
  pkg/exporter/packets.go
  pkg/exporter/packets_proto.go
  pkg/grpc/flow/client.go
  pkg/grpc/flow/grpc_test.go
  pkg/grpc/flow/server.go
  pkg/grpc/packet/client.go
  pkg/grpc/packet/grpc_test.go
  pkg/grpc/packet/server.go
  pkg/pbpacket/packet.pb.go
  pkg/pbpacket/packet_grpc.pb.go
  proto/README.md
  proto/packet.proto
  scripts/agent.yml
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/pipeline/ingest/ingest_grpc.go
Labels: lgtm, approved

#303 Change HOST/PORT env to TARGET_HOST / TARGET_PORT
  README.md
  deployments/flp-daemonset-cap.yml
  deployments/flp-daemonset.yml
  deployments/flp-service.yml
  docs/config.md
  e2e/cluster/base/04-agent.yml
  e2e/ipfix/manifests/30-agent.yml
  examples/flowlogs-dump/README.md
  examples/packetcapture-dump/README.md
  examples/performance/deployment.yml
  examples/systemd/netobserv-ebpf-agent
  pkg/agent/agent.go
  pkg/agent/agent_test.go
  pkg/agent/config.go
  pkg/agent/packets_agent.go
  scripts/agent.yml
Labels: ok-to-test, lgtm, approved

#306 Add go mod vendor check in CI
  .github/workflows/pull_request.yml
Labels: lgtm, approved

#304 NETOBSERV-1545: Expose a counter for BPF hashmap update packets drop
  bpf/flows.c
  bpf/maps_definition.h
  bpf/types.h
  pkg/ebpf/bpf_arm64_bpfel.go
  pkg/ebpf/bpf_arm64_bpfel.o
  pkg/ebpf/bpf_powerpc_bpfel.go
  pkg/ebpf/bpf_powerpc_bpfel.o
  pkg/ebpf/bpf_s390_bpfeb.go
  pkg/ebpf/bpf_s390_bpfeb.o
  pkg/ebpf/bpf_x86_bpfel.go
  pkg/ebpf/bpf_x86_bpfel.o
  pkg/ebpf/tracer.go
  pkg/ebpf/tracer_legacy.go
Labels: jira/valid-reference, lgtm, approved

#305 NETOBSERV-1532: add TLS support to ebpf agent metrics config
  pkg/agent/agent.go
  pkg/agent/config.go
  pkg/metrics/metrics.go
  pkg/prometheus/prom_server.go
Labels: ok-to-test, qe-approved, jira/valid-reference, lgtm, approved
