Repository netobserv/netobserv-ebpf-agent, pull requests merged in 2024-11, with the labels that each got.

#445 Simplify counters manipulation
  bpf/flows.c
  bpf/maps_definition.h
  bpf/network_events_monitoring.h
  bpf/types.h
  bpf/utils.h
  pkg/ebpf/bpf_arm64_bpfel.go
  pkg/ebpf/bpf_arm64_bpfel.o
  pkg/ebpf/bpf_powerpc_bpfel.go
  pkg/ebpf/bpf_powerpc_bpfel.o
  pkg/ebpf/bpf_s390_bpfeb.go
  pkg/ebpf/bpf_s390_bpfeb.o
  pkg/ebpf/bpf_x86_bpfel.go
  pkg/ebpf/bpf_x86_bpfel.o
  pkg/tracer/tracer.go
Labels: no-doc, no-qe, lgtm, approved

#442 Align build steps - distinguish clean vs dev builds
  .github/workflows/push_image.yml
  .github/workflows/push_image_pr.yml
  .github/workflows/release.yml
  Dockerfile
  Makefile
  cmd/netobserv-ebpf-agent.go
Labels: ok-to-test, no-doc, no-qe, lgtm

#435 NETOBSERV-1633 Konflux pipeline multiarch and downstream requirements
  .tekton/netobserv-ebpf-agent-pull-request.yaml
  .tekton/netobserv-ebpf-agent-push.yaml
  .tekton/pipeline-ref.yaml
  Dockerfile.downstream
Labels: lgtm, approved

#447 Fix #446 - Bumped golangci v1.54.2 to v1.61.0 and corrected new lint …
  .golangci.yml
  Makefile
  e2e/cluster/kind.go
  pkg/agent/filter_test.go
  pkg/exporter/grpc_proto_test.go
  pkg/grpc/flow/grpc_test.go
  pkg/grpc/packet/grpc_test.go
  pkg/ifaces/poller_test.go
  pkg/ifaces/registerer_test.go
  pkg/ifaces/watcher.go
  pkg/ifaces/watcher_test.go
  pkg/model/record_test.go
Labels: lgtm, approved, needs-ok-to-test

#464 Fixing konflux results and adding rpms task
  .tekton/pipeline-ref.yaml
Labels: lgtm, approved
