Repository netobserv/netobserv-ebpf-agent, pull requests merged in 2024-06, with the labels that each got.

#344 NETOBSERV-1682: Revert toolchain version
  go.mod
  pkg/pbflow/flow_grpc.pb.go
  pkg/pbpacket/packet_grpc.pb.go
Labels: jira/valid-reference, lgtm, approved

#345 Backport : NETOBSERV-1682: Revert toolchain version
  go.mod
  pkg/pbflow/flow_grpc.pb.go
  pkg/pbpacket/packet_grpc.pb.go
Labels: jira/valid-reference, lgtm, approved

#346 NETOBSERV-1676: make ebpf sampling global and visible to all hooks
  bpf/flows.c
  bpf/pkt_drops.h
  bpf/rtt_tracker.h
  bpf/utils.h
  pkg/ebpf/bpf_arm64_bpfel.o
  pkg/ebpf/bpf_powerpc_bpfel.o
  pkg/ebpf/bpf_s390_bpfeb.o
  pkg/ebpf/bpf_x86_bpfel.o
Labels: ok-to-test, no-qe, jira/valid-reference, lgtm, approved

#349 NETOBSERV-1707: move to go 1.22
  .github/workflows/pull_request.yml
  .github/workflows/pull_request_e2e.yml
  .github/workflows/push_image.yml
  .github/workflows/push_image_pr.yml
  .github/workflows/release.yml
  .golangci.yml
  Dockerfile
  Makefile
  examples/performance/Dockerfile_packet_counter
  pkg/pbflow/flow.pb.go
  pkg/pbpacket/packet.pb.go
  scripts/generators.Dockerfile
Labels: no-doc, no-qe, jira/valid-reference, lgtm, approved

#353 Add .ci-operator.yaml
  .ci-operator.yaml
Labels: lgtm

#358 NETOBSERV-1697: Add retry around netlinkSubscribeAt
  pkg/ebpf/tracer.go
  pkg/ifaces/informer.go
  pkg/ifaces/poller.go
  pkg/ifaces/poller_test.go
  pkg/ifaces/registerer_test.go
  pkg/ifaces/watcher.go
  pkg/ifaces/watcher_test.go
Labels: ok-to-test, qe-approved, jira/valid-reference, lgtm, approved

#359 NETOBSERV-1617: reuse flow filter capability with pcap feature
  bpf/configs.h
  bpf/pca.h
  bpf/types.h
  bpf/utils.h
  cmd/netobserv-ebpf-agent.go
  docs/flow_filtering.md
  examples/packetcapture-dump/README.md
  pkg/agent/agent.go
  pkg/agent/config.go
  pkg/agent/packets_agent.go
  pkg/ebpf/bpf_arm64_bpfel.go
  pkg/ebpf/bpf_arm64_bpfel.o
  pkg/ebpf/bpf_powerpc_bpfel.go
  pkg/ebpf/bpf_powerpc_bpfel.o
  pkg/ebpf/bpf_s390_bpfeb.go
  pkg/ebpf/bpf_s390_bpfeb.o
  pkg/ebpf/bpf_x86_bpfel.go
  pkg/ebpf/bpf_x86_bpfel.o
  pkg/ebpf/flow_filter.go
  pkg/ebpf/flow_filter_test.go
  pkg/ebpf/tracer.go
Labels: no-qe, jira/valid-reference, lgtm, approved

#357 flow filtering default settings for cidr and action
  pkg/agent/config.go
Labels: no-qe, lgtm, approved
