Repository netobserv/netobserv-ebpf-agent, pull requests merged in 2024-07, with the labels that each got.

#360 NETOBSERV-1732: add logic to lkup all previous tc filters and remove them
  pkg/ebpf/tracer.go
Labels: ok-to-test, no-qe, jira/valid-reference, lgtm, approved

#363 NETOBSERV-1743: handle file exits error using TCx hooks and update FC
  pkg/ebpf/tracer.go
Labels: ok-to-test, qe-approved, jira/valid-reference, lgtm, approved

#373 NETOBSERV-1739 move kernel version check to its own pkg
  pkg/ebpf/tracer.go
  pkg/kernel/kernel_utils.go
  pkg/kernel/kernel_utils_test.go
  pkg/utils/utils.go
Labels: no-qe, lgtm, approved

#364 NETOBSERV-1703 Add enrichment in packet capture
  examples/packetcapture-dump/client/packetcapture-client.go
  pkg/agent/agent.go
  pkg/agent/config.go
  pkg/agent/packets_agent.go
  pkg/decode/decode_protobuf.go
  pkg/exporter/direct_flp.go
  pkg/exporter/grpc_packets.go
  pkg/utils/packets.go
Labels: ok-to-test, qe-approved, lgtm, approved
