Repository netobserv/netobserv-ebpf-agent, pull requests merged in 2025-04, with the labels that each got.

#636 bpfman needs to have ns string instead of the nshandle
  pkg/ifaces/informer.go
  pkg/ifaces/poller.go
  pkg/ifaces/poller_test.go
  pkg/ifaces/registerer_test.go
  pkg/ifaces/watcher.go
  pkg/ifaces/watcher_test.go
Labels: lgtm, approved

#538 NETOBSERV-2198: IPsec support
  .mk/bc.mk
  bpf/configs.h
  bpf/flows.c
  bpf/ipsec.h
  bpf/maps_definition.h
  bpf/types.h
  bpf/utils.h
  pkg/agent/agent.go
  pkg/agent/config.go
  pkg/decode/decode_protobuf.go
  pkg/decode/decode_protobuf_test.go
  pkg/ebpf/bpf_arm64_bpfel.go
  pkg/ebpf/bpf_arm64_bpfel.o
  pkg/ebpf/bpf_powerpc_bpfel.go
  pkg/ebpf/bpf_powerpc_bpfel.o
  pkg/ebpf/bpf_s390_bpfeb.go
  pkg/ebpf/bpf_s390_bpfeb.o
  pkg/ebpf/bpf_x86_bpfel.go
  pkg/ebpf/bpf_x86_bpfel.o
  pkg/exporter/converters_test.go
  pkg/model/flow_content.go
  pkg/model/flow_content_test.go
  pkg/pbflow/flow.pb.go
  pkg/pbflow/proto.go
  pkg/tracer/tracer.go
  proto/flow.proto
Labels: jira/valid-reference, lgtm, approved

#654 Decouple config to reduce dependencies in dependants
  cmd/netobserv-ebpf-agent.go
  pkg/agent/agent.go
  pkg/agent/agent_test.go
  pkg/agent/ip.go
  pkg/agent/ip_test.go
  pkg/agent/packets_agent.go
  pkg/agent/sasl.go
  pkg/agent/tls.go
  pkg/config/config.go
Labels: lgtm

#662 NETOBSERV-2215: Add missing IPSec per flow hasIPSec metrics
  pkg/metrics/metrics.go
  pkg/tracer/tracer.go
Labels: ok-to-test, jira/valid-reference, lgtm, approved

#670 Add missing ipsec prom counter to flowenrich definition
  pkg/metrics/metrics.go
Labels: ok-to-test, qe-approved, lgtm, approved

#675 bump fedora 42
  e2e/basic/manifests/pods.yml
  examples/performance/Dockerfile_packet_counter
  pkg/ebpf/bpf_arm64_bpfel.o
  pkg/ebpf/bpf_powerpc_bpfel.o
  pkg/ebpf/bpf_s390_bpfeb.o
  pkg/ebpf/bpf_x86_bpfel.o
  scripts/generators.Dockerfile
Labels: lgtm, approved

#683 Disable cgo on upstream builds and attach binaries to releases
  .github/workflows/release.yml
  .gitignore
  Dockerfile
  Makefile
Labels: lgtm

#684 Simplify previous test fix
  pkg/flow/limiter_test.go
Labels: lgtm
