Repository netobserv/netobserv-ebpf-agent, pull requests merged in 2025-05, with the labels that each got.

#691 NETOBSERV-2186: set sampling field even without filters for consistency
  bpf/flows.c
  pkg/ebpf/bpf_arm64_bpfel.o
  pkg/ebpf/bpf_powerpc_bpfel.o
  pkg/ebpf/bpf_s390_bpfeb.o
  pkg/ebpf/bpf_x86_bpfel.o
Labels: ok-to-test, qe-approved, jira/valid-reference, lgtm

#696 Fix pca - need to unpin ipsec maps
  pkg/tracer/tracer.go
Labels: lgtm

#699 Allow custom registry
  Makefile
Labels: lgtm

#693 NETOBSERV-2101: document needed caps, remove CAP_SYS_RESOURCE
  README.md
  deployments/flp-daemonset-cap.yml
Labels: ok-to-test, qe-approved, jira/valid-reference, lgtm

#708 NETOBSERV-2222: merge ipsec fields in generated map
  bpf/ipsec.h
  bpf/types.h
  pkg/decode/decode_protobuf.go
  pkg/decode/decode_protobuf_test.go
  pkg/ebpf/bpf_arm64_bpfel.go
  pkg/ebpf/bpf_arm64_bpfel.o
  pkg/ebpf/bpf_powerpc_bpfel.go
  pkg/ebpf/bpf_powerpc_bpfel.o
  pkg/ebpf/bpf_s390_bpfeb.go
  pkg/ebpf/bpf_s390_bpfeb.o
  pkg/ebpf/bpf_x86_bpfel.go
  pkg/ebpf/bpf_x86_bpfel.o
  pkg/exporter/converters_test.go
  pkg/model/flow_content.go
  pkg/model/flow_content_test.go
  pkg/pbflow/flow.pb.go
  pkg/pbflow/proto.go
  pkg/tracer/tracer.go
  proto/flow.proto
Labels: jira/valid-reference, needs-review

#703 NETOBSERV-2257: identify interfaces by index and mac
  docs/config.md
  pkg/agent/agent.go
  pkg/agent/packets_agent.go
  pkg/config/config.go
  pkg/exporter/converters_test.go
  pkg/ifaces/filter.go
  pkg/ifaces/filter_test.go
  pkg/ifaces/informer.go
  pkg/ifaces/poller_test.go
  pkg/ifaces/registerer.go
  pkg/ifaces/registerer_test.go
  pkg/ifaces/watcher.go
  pkg/ifaces/watcher_test.go
  pkg/model/packet_record.go
  pkg/model/record.go
  pkg/model/record_test.go
  pkg/tracer/tracer.go
Labels: jira/valid-reference, lgtm, needs-review
