Repository netobserv/netobserv-ebpf-agent, pull requests merged in 2025-01, with the labels that each got.

#497 Change netevents debug logs to trace
  pkg/pbflow/proto.go
Labels: qe-approved, lgtm, approved

#459 Add running doc info
  README.md
Labels: lgtm, approved

#499 NETOBSERV-2031: fix agent verifier issue and userspace crash with no features
  bpf/flows.c
  bpf/types.h
  pkg/ebpf/bpf_arm64_bpfel.o
  pkg/ebpf/bpf_powerpc_bpfel.o
  pkg/ebpf/bpf_s390_bpfeb.o
  pkg/ebpf/bpf_x86_bpfel.o
  pkg/tracer/tracer.go
Labels: ok-to-test, qe-approved, jira/valid-reference, lgtm, approved

#470 NETOBSERV-1996: in-kernel de-duplication
  bpf/flows.c
  bpf/flows_filter.h
  bpf/network_events_monitoring.h
  bpf/pca.h
  bpf/pkt_drops.h
  bpf/pkt_translation.h
  bpf/rtt_tracker.h
  bpf/types.h
  bpf/utils.h
  cmd/netobserv-ebpf-agent.go
  docs/architecture.md
  pkg/agent/agent.go
  pkg/agent/agent_test.go
  pkg/agent/config.go
  pkg/agent/packets_agent.go
  pkg/decode/decode_protobuf.go
  pkg/decode/decode_protobuf_test.go
  pkg/ebpf/bpf_arm64_bpfel.go
  pkg/ebpf/bpf_arm64_bpfel.o
  pkg/ebpf/bpf_powerpc_bpfel.go
  pkg/ebpf/bpf_powerpc_bpfel.o
  pkg/ebpf/bpf_s390_bpfeb.go
  pkg/ebpf/bpf_s390_bpfeb.o
  pkg/ebpf/bpf_x86_bpfel.go
  pkg/ebpf/bpf_x86_bpfel.o
  pkg/ebpf/gen.go
  pkg/exporter/converters_test.go
  pkg/exporter/grpc_proto_test.go
  pkg/exporter/ipfix.go
  pkg/exporter/kafka_proto_test.go
  pkg/flow/account.go
  pkg/flow/account_test.go
  pkg/flow/decorator.go
  pkg/flow/deduper.go
  pkg/flow/deduper_test.go
  pkg/flow/limiter_test.go
  pkg/flow/tracer_map_test.go
  pkg/model/flow_content.go
  pkg/model/flow_content_test.go
  pkg/model/record.go
  pkg/model/record_test.go
  pkg/pbflow/proto.go
  pkg/tracer/tracer.go
  pkg/tracer/tracer_legacy.go
Labels: ok-to-test, qe-approved, jira/valid-reference

#496 Restore performances in filtering case
  bpf/configs.h
  bpf/flows.c
  pkg/ebpf/bpf_arm64_bpfel.o
  pkg/ebpf/bpf_powerpc_bpfel.o
  pkg/ebpf/bpf_s390_bpfeb.o
  pkg/ebpf/bpf_x86_bpfel.o
  pkg/tracer/flow_filter.go
  pkg/tracer/tracer.go
Labels: lgtm, approved

#503 pkt xlat need to align with flow sampling configs
  bpf/pkt_translation.h
  pkg/ebpf/bpf_arm64_bpfel.o
  pkg/ebpf/bpf_powerpc_bpfel.o
  pkg/ebpf/bpf_s390_bpfeb.o
  pkg/ebpf/bpf_x86_bpfel.o
Labels: ok-to-test, lgtm, approved

#505 Add missing , after additional metrics name
  hack/build-bytecode-images-multi.sh
Labels: lgtm, approved

#483 Add enrichment stats
  pkg/metrics/metrics.go
  pkg/tracer/tracer.go
Labels: ok-to-test, lgtm, approved

#508 NETOBSERV-2055: Xlat ICMP code is redundant with icmp code field so removing it
  bpf/pkt_translation.h
  bpf/types.h
  bpf/utils.h
  pkg/decode/decode_protobuf.go
  pkg/decode/decode_protobuf_test.go
  pkg/ebpf/bpf_arm64_bpfel.go
  pkg/ebpf/bpf_arm64_bpfel.o
  pkg/ebpf/bpf_powerpc_bpfel.go
  pkg/ebpf/bpf_powerpc_bpfel.o
  pkg/ebpf/bpf_s390_bpfeb.go
  pkg/ebpf/bpf_s390_bpfeb.o
  pkg/ebpf/bpf_x86_bpfel.go
  pkg/ebpf/bpf_x86_bpfel.o
  pkg/model/record_test.go
  pkg/pbflow/flow.pb.go
  pkg/pbflow/proto.go
  proto/flow.proto
Labels: ok-to-test, qe-approved, jira/valid-reference, lgtm, approved

#510 Always set the additional map size
  pkg/tracer/tracer.go
Labels: lgtm, approved

#519 NETOBSERV-2028 handle bc images in makefile
  .github/workflows/push_image.yml
  .github/workflows/push_image_pr.yml
  .mk/bc.mk
  .mk/shortcuts.mk
  Makefile
  hack/build-bytecode-images-multi.sh
Labels: ok-to-test, lgtm, approved

#501 NETOBSERV-2047: Add peerCIDR support
  .mk/bc.mk
  bpf/flows_filter.h
  bpf/maps_definition.h
  bpf/types.h
  docs/flow_filtering.md
  pkg/agent/agent.go
  pkg/agent/config.go
  pkg/agent/packets_agent.go
  pkg/ebpf/bpf_arm64_bpfel.go
  pkg/ebpf/bpf_arm64_bpfel.o
  pkg/ebpf/bpf_powerpc_bpfel.go
  pkg/ebpf/bpf_powerpc_bpfel.o
  pkg/ebpf/bpf_s390_bpfeb.go
  pkg/ebpf/bpf_s390_bpfeb.o
  pkg/ebpf/bpf_x86_bpfel.go
  pkg/ebpf/bpf_x86_bpfel.o
  pkg/tracer/flow_filter.go
  pkg/tracer/flow_filter_test.go
  pkg/tracer/tracer.go
Labels: ok-to-test, jira/valid-reference, lgtm, approved

#521 Add test -race
  .github/workflows/pull_request.yml
  Makefile
  pkg/agent/agent_test.go
  pkg/model/record_test.go
Labels: no-doc, no-qe

#520 Avoid using reference to ovnk udn map and create a copy instead
  pkg/exporter/converters_test.go
  pkg/exporter/grpc_proto_test.go
  pkg/exporter/kafka_proto_test.go
  pkg/flow/account_test.go
  pkg/flow/limiter_test.go
  pkg/model/record.go
Labels: ok-to-test, lgtm, approved

#509 NETOBSERV-2075: Simplifying observed interfaces - moving it to main map
  bpf/flows.c
  bpf/types.h
  bpf/utils.h
  pkg/agent/agent_test.go
  pkg/ebpf/bpf_arm64_bpfel.go
  pkg/ebpf/bpf_arm64_bpfel.o
  pkg/ebpf/bpf_powerpc_bpfel.go
  pkg/ebpf/bpf_powerpc_bpfel.o
  pkg/ebpf/bpf_s390_bpfeb.go
  pkg/ebpf/bpf_s390_bpfeb.o
  pkg/ebpf/bpf_x86_bpfel.go
  pkg/ebpf/bpf_x86_bpfel.o
  pkg/ebpf/gen.go
  pkg/exporter/grpc_proto.go
  pkg/exporter/kafka_proto.go
  pkg/flow/tracer_ringbuf.go
  pkg/metrics/metrics.go
  pkg/model/flow_content.go
  pkg/model/flow_content_test.go
  pkg/model/record.go
  pkg/model/record_test.go
  pkg/tracer/tracer.go
  pkg/tracer/tracer_legacy.go
Labels: ok-to-test, qe-approved, jira/valid-reference, lgtm, approved

#523 OCPBUGS-48838: replace bpf_probe_read by bpf_probe_read_kernel()
  bpf/network_events_monitoring.h
  bpf/pkt_drops.h
  bpf/pkt_translation.h
  bpf/utils.h
  pkg/ebpf/bpf_arm64_bpfel.o
  pkg/ebpf/bpf_powerpc_bpfel.o
  pkg/ebpf/bpf_s390_bpfeb.o
  pkg/ebpf/bpf_x86_bpfel.o
Labels: ok-to-test, qe-approved, jira/valid-reference, lgtm, jira/invalid-bug

#528 NETOBSERV-2081: Cache and load UDN maps only when udn is enabled
  pkg/agent/agent.go
  pkg/exporter/converters_test.go
  pkg/exporter/grpc_proto_test.go
  pkg/exporter/kafka_proto_test.go
  pkg/flow/account.go
  pkg/flow/account_test.go
  pkg/flow/limiter_test.go
  pkg/flow/tracer_map.go
  pkg/model/record.go
  pkg/model/record_test.go
Labels: ok-to-test, jira/valid-reference, lgtm, approved

#534 NETOBSERV-2051: Fix eBPF verifier errors with 5.14.0-284.71.1.el9_2
  bpf/flows.c
  bpf/network_events_monitoring.h
  bpf/pkt_drops.h
  bpf/pkt_translation.h
  bpf/rtt_tracker.h
  pkg/ebpf/bpf_arm64_bpfel.o
  pkg/ebpf/bpf_powerpc_bpfel.o
  pkg/ebpf/bpf_s390_bpfeb.o
  pkg/ebpf/bpf_x86_bpfel.o
Labels: qe-approved, jira/valid-reference, lgtm, approved

#540 NETOBSERV-2084: (nit) no need to copy map anymore [backport 1.8]
  pkg/pbflow/proto.go
Labels: jira/valid-reference, lgtm

#537 NETOBSERV-2077: switch to syncMap to handle concurrency issues [BP 1.8]
  pkg/ifaces/watcher.go
Labels: ok-to-test, jira/valid-reference, lgtm, approved

#535 NETOBSERV-2077: use syncMap to handle concurrency issues in intf watcher
  pkg/ifaces/watcher.go
Labels: ok-to-test, qe-approved, jira/valid-reference, lgtm, approved

#541 update actions/upload-artifact to v4
  .github/workflows/pull_request_e2e.yml
Labels: lgtm, approved
